import assert from 'node:assert/strict';
import test from 'node:test';
import { readFileSync } from 'node:fs';
import { workspaceRegistry } from '../src/workspace-engine/registry';
import { createWorkspaceDefinition } from '../src/workspace-engine/workspaceFactory';
import { createOfficialWorkspaceDefinition, OFFICIAL_WORKSPACE_TEMPLATES } from '../src/workspace-engine/workspaceOfficialFactory';

test('official instances are generated by the Workspace Factory', () => {
  assert.deepEqual(
    workspaceRegistry,
    OFFICIAL_WORKSPACE_TEMPLATES.map(template => createOfficialWorkspaceDefinition(template.id)),
  );
  assert.deepEqual(workspaceRegistry.map(item => item.id), [
    'workspace-governanca',
    'workspace-recepcao',
    'workspace-operacao',
    'workspace-manutencao',
    'workspace-cozinha',
    'workspace-financeiro',
    'workspace-administrativo-hotel',
    'workspace-administrativo-sistema',
  ]);
});

test('factory cutover preserves historical base ids and widget ids', () => {
  const governance = createOfficialWorkspaceDefinition('workspace-governanca');
  const reception = createOfficialWorkspaceDefinition('workspace-recepcao');

  assert.equal(governance.widgets.some(widget => widget.id === 'governanca-kanban'), true);
  assert.equal(reception.widgets.some(widget => widget.id === 'recepcao-reservas'), true);
  assert.equal(reception.widgets.some(widget => widget.id === 'recepcao-calendario-ocupacao'), true);
  assert.equal(reception.widgets.some(widget => widget.id === 'recepcao-kanban'), true);
});

test('new official sectors reuse the existing sector compositions', () => {
  const cases = [
    { id: 'workspace-operacao' as const, name: 'Operação Geral', sector: 'operacao' as const },
    { id: 'workspace-manutencao' as const, name: 'Manutenção', sector: 'manutencao' as const },
    { id: 'workspace-cozinha' as const, name: 'Cozinha & Room Service', sector: 'cozinha' as const },
  ];

  for (const item of cases) {
    assert.deepEqual(
      createOfficialWorkspaceDefinition(item.id).widgets,
      createWorkspaceDefinition(item).widgets,
    );
  }
});

test('Workspaces Financeiro e Administrativos são layouts de gestão e não criam setores artificiais', () => {
  const financial = createOfficialWorkspaceDefinition('workspace-financeiro');
  const administrativeHotel = createOfficialWorkspaceDefinition('workspace-administrativo-hotel');
  const administrativeSystem = createOfficialWorkspaceDefinition('workspace-administrativo-sistema');
  const legacyAdministrative = createOfficialWorkspaceDefinition('workspace-administrativo');

  assert.equal(financial.layout, 'management');
  assert.equal(financial.defaultScope, 'mine');
  assert.deepEqual(financial.sectors, []);

  for (const administrative of [administrativeHotel, administrativeSystem]) {
    assert.equal(administrative.layout, 'management');
    assert.equal(administrative.defaultScope, 'mine');
    assert.deepEqual(administrative.sectors, []);
  }
  assert.equal(legacyAdministrative.id, 'workspace-administrativo-hotel');
  assert.deepEqual(administrativeHotel.widgets.map(widget => widget.type), [
    'hotel-os-admin',
    'user-access',
    'automation-admin',
    'settings-admin',
  ]);
  assert.deepEqual(administrativeSystem.widgets.map(widget => widget.type), [
    'user-access',
    'settings-admin',
    'hotel-os-admin',
  ]);
});

test('registry no longer declares official Workspace objects by hand', () => {
  const source = readFileSync(new URL('../src/workspace-engine/registry.ts', import.meta.url), 'utf8');
  assert.match(source, /createOfficialWorkspaceDefinitions\(\)/);
  assert.doesNotMatch(source, /id:\s*['"]workspace-governanca['"]/);
  assert.doesNotMatch(source, /id:\s*['"]workspace-recepcao['"]/);
  assert.doesNotMatch(source, /id:\s*['"]workspace-operacao['"]/);
  assert.doesNotMatch(source, /id:\s*['"]workspace-manutencao['"]/);
  assert.doesNotMatch(source, /id:\s*['"]workspace-cozinha['"]/);
  assert.doesNotMatch(source, /id:\s*['"]workspace-financeiro['"]/);
  assert.doesNotMatch(source, /id:\s*['"]workspace-administrativo['"]/);
  assert.doesNotMatch(source, /widgets:\s*normalizeWorkspaceWidgets/);
});
